name: server-home-jira

services:
  jira:
    image: atlassian/jira-software:latest
    container_name: jira
    restart: unless-stopped
    depends_on:
      - jira-db
    environment:
      ATL_JDBC_URL: jdbc:postgresql://jira-db:5432/${JIRA_DB_NAME}
      ATL_JDBC_USER: ${JIRA_DB_USER}
      ATL_JDBC_PASSWORD: ${JIRA_DB_PASSWORD}
      ATL_PROXY_NAME: ${JIRA_DOMAIN}
      ATL_PROXY_PORT: ${JIRA_PROXY_PORT}
      ATL_TOMCAT_SCHEME: ${JIRA_TOMCAT_SCHEME}
      ATL_TOMCAT_SECURE: ${JIRA_TOMCAT_SECURE}
    ports:
      - "${JIRA_HTTP_PORT}:8080"
    volumes:
      - ./volumes/jira-home:/var/atlassian/application-data/jira

  jira-db:
    image: postgres:15
    container_name: jira-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${JIRA_DB_NAME}
      POSTGRES_USER: ${JIRA_DB_USER}
      POSTGRES_PASSWORD: ${JIRA_DB_PASSWORD}
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
